openapi: '3.0.3'

info:
  title: 'Shop Review API'
  version: '1.0.0'

servers:
  - url: 'http://localhost:{port}'
    description: 'Local development'
    variables:
      port:
        enum: ['3000', '8000']
        default: '3000'
  - url: 'https://it1.shopreview.com'
    description: 'Integration Test'
  - url: 'https://stg.shopreview.com'
    description: 'Staging Test'
  - url: 'https://api.shopreview.com'
    description: 'Production'

paths: {}
