# レビュー情報投稿APIの作成
# POST /shops/{shopId}/reviews

# 201番
# locationヘッダーで新しいURLを通知

# 400番
# エラー詳細をレスポンスボディに表現
# {
#   code: "1234",
#   type: "InvalidDataFormat"
#   message: "Invalid data"
#   errors: [{
#     field: "comment",
#     code: "1234-001"
#   }]
# }

openapi: '3.0.3'

info:
  title: 'Shop Review API'
  version: '1.0.0'

paths:
  '/shops/{shopId}/reviews':
    post:
      summary: 'Create review'
      parameters:
        - name: shopId
          in: path
          required: true
          schema: { type: string }
      requestBody:
        description: 'Contents of review'
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                score: { type: integer, example: 3 }
                comment: { type: string, example: 'Delicious' }
      responses:
        '201':
          description: 'Success operation'
          headers:
            location:
              description: 'New URL of created review'
              schema: { type: string, format: url }
        '400':
          description: 'Client side error'
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: string }
                  type: { type: string }
                  message: { type: string }
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field: { type: string }
                        code: { type: string }
