# サンプルSchemaの作成

# 0以上10未満の整数
# null許容する10文字〜20文字の文字列
# 真偽値

openapi: '3.0.3'

info:
  title: 'Shop Review API'
  version: '1.0.0'

paths: {}

components:
  schemas:
    SampleInt:
      type: integer
      minimum: 0
      exclusiveMinimum: false
      maximum: 100
      exclusiveMaximum: true
    SampleString:
      type: string
      nullable: true
      minLength: 10
      maxLength: 20
    SampleBoolean:
      type: boolean
